name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Musl
        run: sudo apt install -y musl musl-tools

      - name: Install LibUdev
        run: sudo apt install -y libudev-dev

      - name: Update Rust
        run: rustup update

      - name: Add Musl Target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build Forge
        run: ./build-forge.sh